### ISSUE TITLE
Could you explain how to install/run?

### ISSUE THREAD

**Issue by pulketo** [arsham/blush#5]
Could you explain how to install/run?
I've already installed golang... what then, I'm on ubuntu, but i suppose it's quite similar for everyones go installation.

**Comment by embano1** [comment]
@pulketo If you have a working Go environment, please first check

```
$ echo $GOPATH
$ echo $GOBIN
```

$GOBIN is where your binary will land, $GOPATH is always required to be set correctly, e.g.

```
$ export GOPATH=~/Go
$ export GOBIN=~/Go/bin
$ export PATH=$PATH:$GOBIN
```

Then you're good to go:

```
$ go get -x -u -v github.com/arsham/blush/
```

`blush` will be installed into $GOBIN. Depending on your shell, you might need to execute `rehash` before the new binary will be picked up in your path. Then just type `blush`.

**Comment by arsham** [comment]
Thank you for bringing up this issue. I will update the **README** file and will produce release binaries.
